test

diff --git a/.github/workflows/code-coverage.yml b/.github/workflows/code-coverage.yml
--- a/.github/workflows/code-coverage.yml
+++ b/.github/workflows/code-coverage.yml
@@ -13,8 +13,8 @@ env:
   ENABLE_UNIT_TESTS: true
   OMIT_DEPRECATED: true
   BUILDTYPE: debug
-  ALLOWED_MISSED_BRANCHES: 38
-  ALLOWED_MISSED_LINES: 17
+  ALLOWED_MISSED_BRANCHES: 39
+  ALLOWED_MISSED_LINES: 16
   ALLOWED_MISSED_FUNCTIONS: 0
 jobs:
 
@@ -121,21 +121,21 @@ jobs:
           if [ $branch_diff -gt ${{ env.ALLOWED_MISSED_BRANCHES }} ]
           then
             grep -A 3 "Overall coverage rate" lcov_out.txt
-            echo "::error::$branch_diff uncovered branch$([ $branch_diff -eq 1 ] && echo '' || echo 'es') reported, but ${{ env.ALLOWED_MISSED_BRANCHES }} $([ $branch_diff -eq 1 ] && echo 'is' || echo 'are') allowed."
+            echo "::error::$branch_diff uncovered branch$([ $branch_diff -eq 1 ] && echo '' || echo 'es') reported, but only ${{ env.ALLOWED_MISSED_BRANCHES }} $([ $branch_diff -eq 1 ] && echo 'is' || echo 'are') allowed."
             exit -1
           fi
 
           if [ $line_diff -gt ${{ env.ALLOWED_MISSED_LINES }} ]
           then
             grep -A 3 "Overall coverage rate" lcov_out.txt
-            echo "::error::$line_diff uncovered line$([ $line_diff -eq 1 ] && echo '' || echo 's') reported, but ${{ env.ALLOWED_MISSED_LINES }} $([ $line_diff -eq 1 ] && echo 'is' || echo 'are') allowed."
+            echo "::error::$line_diff uncovered line$([ $line_diff -eq 1 ] && echo '' || echo 's') reported, but only ${{ env.ALLOWED_MISSED_LINES }} $([ $line_diff -eq 1 ] && echo 'is' || echo 'are') allowed."
             exit -1
           fi
 
           if [ $function_diff -gt ${{ env.ALLOWED_MISSED_FUNCTIONS }} ]
           then
             grep -A 3 "Overall coverage rate" lcov_out.txt
-            echo "::error::$function_diff uncovered function$([ $function_diff -eq 1 ] && echo '' || echo 's') reported, but ${{ env.ALLOWED_MISSED_FUNCTIONS }} $([ $function_diff -eq 1 ] && echo 'is' || echo 'are') allowed."
+            echo "::error::$function_diff uncovered function$([ $function_diff -eq 1 ] && echo '' || echo 's') reported, but only ${{ env.ALLOWED_MISSED_FUNCTIONS }} $([ $function_diff -eq 1 ] && echo 'is' || echo 'are') allowed."
             exit -1
           fi
 
