test

diff --git a/.github/workflows/code-coverage.yml b/.github/workflows/code-coverage.yml
--- a/.github/workflows/code-coverage.yml
+++ b/.github/workflows/code-coverage.yml
@@ -134,7 +134,7 @@ jobs:
           if [ $branch_diff -lt ${{ env.ALLOWED_MISSED_BRANCHES }} ]
           then
             grep -A 3 "Overall coverage rate" lcov_out.txt
-            echo "::error::$branch_diff uncovered branch${branch_diff == 1 && '' || 'es'} reported, but ${{ env.ALLOWED_MISSED_BRANCHES }} ${branch_diff == 1 && 'is' || 'are'} allowed."
+            echo "::error::$branch_diff uncovered branch$( [ $branch_diff -eq 1 ] && echo '' || echo 'es' ) reported, but ${{ env.ALLOWED_MISSED_BRANCHES }} $( [ ${{ env.ALLOWED_MISSED_BRANCHES }} -eq 1 ] && echo 'is' || echo 'are' ) allowed."
             echo "::error::Please update (lower) the 'ALLOWED_MISSED_BRANCHES' variable to $branch_diff in order to match the new coverage level."
             exit -1
           fi
@@ -144,7 +144,7 @@ jobs:
           if [ $line_diff -lt ${{ env.ALLOWED_MISSED_LINES }} ]
           then
             grep -A 3 "Overall coverage rate" lcov_out.txt
-            echo "::error::$line_diff uncovered line${line_diff == 1 && '' || 's'} reported, but ${{ env.ALLOWED_MISSED_LINES }} ${line_diff == 1 && 'is' || 'are'} allowed."
+            echo "::error::$line_diff uncovered line$( [ $line_diff -eq 1 ] && echo '' || echo 's' ) reported, but ${{ env.ALLOWED_MISSED_LINES }} $( [ ${{ env.ALLOWED_MISSED_LINES }} -eq 1 ] && echo 'is' || echo 'are' ) allowed."
             echo "::error::Please update (lower) the 'ALLOWED_MISSED_LINES' variable to $line_diff in order to match the new coverage level."
             exit -1
           fi
